# Generated by Django 3.1.5 on 2021-02-15 14:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0017_auto_20210215_1459'),
    ]

    operations = [
        migrations.CreateModel(
            name='Problem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=None, max_length=50)),
                ('desc', models.CharField(default=None, max_length=200, null=True)),
                ('difficulty', models.CharField(max_length=20)),
                ('hashes', models.JSONField()),
                ('inputs', models.JSONField()),
                ('date_created', models.DateField()),
                ('analysis', models.JSONField(default=dict)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.profile')),
            ],
        ),
        migrations.CreateModel(
            name='Solution',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('analysis', models.JSONField()),
                ('date_submitted', models.DateField()),
                ('problem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='code_analysis.problem')),
                ('submitter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.profile')),
            ],
            options={
                'unique_together': {('submitter', 'problem')},
            },
        ),
    ]
