# Generated by Django 3.1.5 on 2021-02-20 17:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_auto_20210215_1459'),
        ('code_analysis', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='problem',
            unique_together={('author', 'name')},
        ),
    ]
