# Generated by Django 3.1.5 on 2021-03-07 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('code_analysis', '0004_auto_20210220_1819'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='problem',
            name='date_created',
        ),
        migrations.RemoveField(
            model_name='problem',
            name='desc',
        ),
        migrations.RemoveField(
            model_name='problem',
            name='difficulty',
        ),
        migrations.AddField(
            model_name='problem',
            name='metadata',
            field=models.JSONField(default=dict),
        ),
    ]
