# Generated by Django 3.1.5 on 2021-03-14 17:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('code_analysis', '0005_auto_20210307_1554'),
    ]

    operations = [
        migrations.RenameField(
            model_name='problem',
            old_name='hashes',
            new_name='outputs',
        ),
    ]
