# Generated by Django 3.1.5 on 2021-03-18 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('code_analysis', '0006_auto_20210314_1723'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='data',
            field=models.JSONField(default=dict),
        ),
    ]
