# Generated by Django 3.1.5 on 2021-03-18 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('code_analysis', '0008_auto_20210318_2222'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problem',
            name='supplied_data',
            field=models.JSONField(default=list),
        ),
    ]
