# Generated by Django 3.1.5 on 2021-03-19 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('code_analysis', '0010_auto_20210319_1341'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problem',
            name='init_data',
            field=models.JSONField(null=True),
        ),
    ]
