# Generated by Django 3.1.5 on 2021-03-21 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('code_analysis', '0011_auto_20210319_1558'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='category',
            field=models.CharField(default='default', max_length=50),
            preserve_default=False,
        ),
    ]
