# Generated by Django 3.1.5 on 2021-03-21 18:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('code_analysis', '0012_problem_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='problem',
            name='category',
        ),
    ]
