# Generated by Django 3.1.5 on 2021-07-24 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('code_analysis', '0014_problem_date_submitted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problem',
            name='inputs',
            field=models.JSONField(null=True),
        ),
    ]
