# Generated by Django 3.1.5 on 2021-10-08 15:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0001_initial'),
        ('code_analysis', '0015_auto_20210724_2144'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='course',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='classes.course'),
        ),
    ]
