# Generated by Django 3.1.5 on 2021-10-12 18:52

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0004_auto_20211009_1840'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('code_analysis', '0019_auto_20211012_1838'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='solution',
            unique_together={('submitter', 'problem', 'course_id')},
        ),
    ]
