# Generated by Django 3.1.5 on 2021-10-23 17:14

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('classes', '0004_auto_20211009_1840'),
        ('code_analysis', '0020_auto_20211012_1852'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solution',
            name='date_submitted',
            field=models.DateTimeField(),
        ),
        migrations.AlterUniqueTogether(
            name='solution',
            unique_together={('submitter', 'problem', 'course_id', 'date_submitted')},
        ),
    ]
