# Generated by Django 3.1.5 on 2021-10-09 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0002_course_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='code',
            field=models.CharField(default='courseX', max_length=100, null=True),
        ),
    ]
