# Generated by Django 3.1.5 on 2021-02-06 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20210206_1624'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='desc',
            field=models.CharField(default=None, max_length=200),
        ),
    ]
