# Generated by Django 3.1.5 on 2021-02-11 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_problem_analysis'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problem',
            name='analysis',
            field=models.JSONField(default={}),
        ),
    ]
