# Generated by Django 3.1.5 on 2021-02-11 16:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_auto_20210211_1148'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='submission',
            unique_together={('user_id', 'problem_id')},
        ),
    ]
