# Generated by Django 3.1.5 on 2021-02-11 16:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_auto_20210211_1605'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Submission',
            new_name='Solution',
        ),
    ]
