# Generated by Django 3.1.5 on 2021-02-14 14:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_auto_20210214_1457'),
    ]

    operations = [
        migrations.RenameField(
            model_name='solution',
            old_name='user',
            new_name='submitter',
        ),
        migrations.AlterUniqueTogether(
            name='solution',
            unique_together={('submitter', 'problem')},
        ),
    ]
