# Generated by Django 3.1.5 on 2021-02-14 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_auto_20210214_1517'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='rank',
            field=models.IntegerField(null=True),
        ),
    ]
