# Generated by Django 3.1.5 on 2021-02-15 14:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_auto_20210214_1621'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='solution',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='solution',
            name='problem',
        ),
        migrations.RemoveField(
            model_name='solution',
            name='submitter',
        ),
        migrations.DeleteModel(
            name='Problem',
        ),
        migrations.DeleteModel(
            name='Solution',
        ),
    ]
